version: '3.0'

tasks:

  default:
    desc: Install dependencies, download data, build docker images and spin the service containers
    cmds:
      - task: download
      - task: process
      - task: start 

  download:
    desc: Download and sanitize required data
    cmds:
      - touch data/raw/title.ratings.tsv data/raw/title.basics.tsv
      - wget -O - https://datasets.imdbws.com/title.ratings.tsv.gz | gzip -d > data/raw/title.ratings.tsv 
      - wget -O - https://datasets.imdbws.com/title.basics.tsv.gz | gzip -d > data/raw/title.basics.tsv

  process:
    dir: data
    cmds:
      - python process.py

  clean:
    desc: Remove stopped service containers 
    cmds:
      - docker compose rm -f

  build:
    desc: Build docker images for the service containers
    cmds:
      - task: clean
      - docker compose build

  run:
    desc: Run database and backend service containers
    cmds:
      - docker compose up
  
  start:
    desc: Run database and backend service containers
    cmds:
      - task: clean
      - task: build
      - docker compose up