version: '3.0'

tasks:
  default:

    desc: Process data 

    dir: packages/data

    cmds:
      - docker build -f Dockerfile . -t sps-setup
      - |
        docker run  \
        --mount type=bind,source="$(pwd)/raw",target=/app/raw \
        --mount type=bind,source="$(pwd)/processed",target="/app/processed" \
        -it sps-setup:latest
#-----------------------------------------------------------------------
  generate:tsung:query-set:
    
    descr: Build the query set. Generate 10_000 random ids according to the rating probability

    dir: packages/tsung

    cmds:
      - python3 query_builder.py
#-----------------------------------------------------------------------
  build:server:development:

    desc: Runs the server stack in development mode

    dir: packages/server

    vars:
      BACKEND_REPLICAS: 1
    
    preconditions: 
      - sh: test -f ../data/processed/title.basics.tsv
        msg: MIGRATION DATA MISSING. Launch task in the terminal
      - sh: test -f ../data/processed/title.ratings.tsv
        msg: RATING DATA MISSING. Launch task in the terminal
    
    cmds:
      - docker compose -f docker-compose.yml up --scale backend={{ .BACKEND_REPLICAS }}
#-----------------------------------------------------------------------
  build:server:testing:

    desc: Runs the server stack in testing mode

    dir: packages/server

    vars:
      BACKEND_REPLICAS: 1
    
    preconditions: 
      - sh: test -f ../data/processed/title.basics.tsv
        msg: MIGRATION DATA MISSING. Launch task in the terminal
      - sh: test -f ../data/processed/title.ratings.tsv
        msg: RATING DATA MISSING. Launch task in the terminal
    
    cmds:
      - docker compose -f docker-compose_testing.yml up --scale backend={{ .BACKEND_REPLICAS }}
#-----------------------------------------------------------------------
  run:tsung:bottleneck_test:

    desc: Perform tsung closed-loop test

    dir: packages/tsung
    
    vars:
      TSUNG_HOST: 192.168.1.18
      TSUNG_PORT: 3000
      TSUNG_LOG_DIR: ./logs
      TSUNG_MAXUSERS: 7500
      TSUNG_MAXDURATION: 18
      TSUNG_ARRIVALPHASE_DURATION: 13
      TSUNG_ARRIVALPHASE_RATE: 18
      TSUNG_USER_REQUESTS: 1000
      FAST_QUERY: /title_details?tconst=eq.
      SLOW_QUERY: /rpc/get_title_details?tconstvar=

    preconditions:
      - sh: test -f queries.csv
        msg: "QUERY SET MISSING. Generate it with task generate:tsung:query-set"
      - sh:  test ! -z "$(curl -Is http://{{.TSUNG_HOST}}:{{.TSUNG_PORT}} | head -1)"
        msg: SUT (http://{{.TSUNG_HOST}}:{{.TSUNG_PORT}}) IS NOT REACHABLE. Have you run task run:server:development or run:server:testing?

    cmds:
      - python3 tsung_config.py --host {{.TSUNG_HOST}}
                               --port {{.TSUNG_PORT}}
                               --maxusers {{.TSUNG_MAXUSERS}}
                               --maxduration {{.TSUNG_MAXDURATION}}
                               --arrivalduration {{.TSUNG_ARRIVALPHASE_DURATION}}
                               --arrivalrate {{.TSUNG_ARRIVALPHASE_RATE}}
                               --userequests {{.TSUNG_USER_REQUESTS}}
                               --query {{.FAST_QUERY}} > tsung_config.xml

      - tsung -k -l {{ .TSUNG_LOG_DIR }} -f ./tsung_config.xml start
#-----------------------------------------------------------------------
  run:tsung:db_test:
  
    desc: Perform a single-user tsung closed-loop test against Postregresql DB

    dir: packages/tsung

    vars:
      TSUNG_HOST: 192.168.1.18
      TSUNG_PORT: 5433
      TSUNG_LOG_DIR: ./logs/db_logs
      TSUNG_MAXUSERS: 1
      TSUNG_MAXDURATION: 7
      TSUNG_ARRIVALPHASE_DURATION: 5
      TSUNG_ARRIVALPHASE_RATE: 1
      TSUNG_USER_REQUESTS: 10000

    preconditions:
      - sh: test -f queries.csv
        msg: "QUERY SET MISSING. Generate it with task generate:tsung:query-set"

    cmds:
      - python3 tsung_config_db.py --host {{.TSUNG_HOST}}
                               --port {{.TSUNG_PORT}}
                               --maxusers {{.TSUNG_MAXUSERS}}
                               --maxduration {{.TSUNG_MAXDURATION}}
                               --arrivalduration {{.TSUNG_ARRIVALPHASE_DURATION}}
                               --arrivalrate {{.TSUNG_ARRIVALPHASE_RATE}}
                               --userequests {{.TSUNG_USER_REQUESTS}} > tsung_config_db.xml

      - tsung -k -l {{ .TSUNG_LOG_DIR }} -f ./tsung_config_db.xml start
#-----------------------------------------------------------------------
  run:tsung:1u_test:
  
    desc: Perform a single-user tsung closed-loop test
    dir: packages/tsung

    vars:
      TSUNG_HOST: 192.168.1.18
      TSUNG_PORT: 3000
      TSUNG_LOG_DIR: ./logs/1u_logs
      TSUNG_MAXDURATION: 7
      TSUNG_ARRIVALPHASE_DURATION: 5
      TSUNG_USER_REQUESTS: 10000
      FAST_QUERY: /title_details?tconst=eq.
      SLOW_QUERY: /rpc/get_title_details?tconstvar=

    preconditions:
      - sh: test -f queries.csv
        msg: "QUERY SET MISSING. Generate it with task generate:tsung:query-set"
      - sh:  test ! -z "$(curl -Is http://{{.TSUNG_HOST}}:{{.TSUNG_PORT}} | head -1)"
        msg: SUT (http://{{.TSUNG_HOST}}:{{.TSUNG_PORT}}) IS NOT REACHABLE. Have you run task run:server:development or run:server:testing?

    cmds:
      - python3 tsung_config_1u.py --host {{.TSUNG_HOST}}
                               --port {{.TSUNG_PORT}}
                               --maxduration {{.TSUNG_MAXDURATION}}
                               --arrivalduration {{.TSUNG_ARRIVALPHASE_DURATION}}
                               --userequests {{.TSUNG_USER_REQUESTS}}
                               --query {{.FAST_QUERY}} > tsung_config_1u.xml

      - tsung -k -l {{ .TSUNG_LOG_DIR }} -f ./tsung_config_1u.xml start
#-----------------------------------------------------------------------
  update:db-functions:
    cmds:
      - docker exec -it server-db-1 psql -U authenticator -d imdb -f ./sqlFiles/02_functions.sql

  update:db-views:
    cmds:
      - docker exec -it server-db-1 psql -U authenticator -d imdb -f ./sqlFiles/01_views.sql

