version: '3.0'

tasks:
  default:

    desc: Process data 

    dir: packages/data
    
    cmds:
      - docker build -f Dockerfile . -t sps-setup
      - |
        docker run  \
        --mount type=bind,source="$(pwd)/raw",target=/app/raw \
        --mount type=bind,source="$(pwd)/processed",target="/app/processed" \
        -it sps-setup:latest

  run:server:

    desc: Runs the server stack

    dir: packages/server
    
    preconditions: 
      - test -f ../data/processed/title.basics.tsv
      - test -f ../data/processed/title.ratings.tsv

    cmds:
      - docker compose up
  
  run:client:
    
    desc: Runs the client web app
    
    dir: packages/client
    
    cmds:
      - echo TODO

