# CONFIGURATION FOR PROJECT DEVELOPMENT

version: '2.4'

services:

  db:
    image: postgres
    environment:
      POSTGRES_DB: imdb
      POSTGRES_USER: authenticator
      POSTGRES_PASSWORD: sps
      # POSTGRES_HOST_AUTH_METHOD: trust
    # Reources Limits
    mem_limit: 1024m
    mem_reservation: 64M
    cpus: 0.4
    ports:
    # Maps port 5433 on localhost to port 5432 of the container
      - "5433:5432"
    volumes:
      - ./sql/:/docker-entrypoint-initdb.d/
      - ./sql/:/sqlFiles/
      - ../data/processed/title.basics.tsv:/data/title.basics.tsv
      - ../data/processed/title.ratings.tsv:/data/title.ratings.tsv
      - ../data/processed/title.crew.tsv:/data/title.crew.tsv
      - ../data/processed/title.episode.tsv:/data/title.episode.tsv
      # - ../data/processed/title.principals.tsv:/data/title.principals.tsv
      # - ../data/processed/name.basics.tsv:/data/name.basics.tsv
      # - ./sql/postgresql.conf:/var/lib/postgresql/data/postgresql.conf
      # - ./sql/pg_hba.conf:/var/lib/postgresql/data/pg_hba.conf
      # - ./sql/logs/:/var/lib/postgresql/data/logs/


  backend:
    image: postgrest/postgrest
    environment:
      PGRST_SERVER_PORT: 3001
      PGRST_DB_URI: postgres://authenticator:sps@db:5432/imdb
      PGRST_DB_SCHEMAS: "imdb"
      PGRST_DB_ANON_ROLE: "web_anon"
    # Resources Limits
    mem_limit: 512m
    mem_reservation: 64M
    cpus: 0.25
    ports:
      -"3001:3001"
    depends_on:
      - db


  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    # Resources Limits
    mem_limit: 256m
    mem_reservation: 64M
    cpus: 0.25
    ports:
      - "3000:80"
    depends_on:
      - db


  swagger:
    image: swaggerapi/swagger-ui
    # Resources Limits
    mem_limit: 128m
    cpus: 0.05
    ports:
      - "3001:8080"
    expose:
      - "8080"
    environment:
      API_URL: http://localhost:3000/