# CONFIGURATION FOR PERFORMANCE ANALYSIS

version: '3.1'

services:

  db:
    image: postgres
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: imdb
      POSTGRES_USER: authenticator
      POSTGRES_PASSWORD: sps
    volumes:
      - ./00_migrate.sql:/docker-entrypoint-initdb.d/00_migrate.sql
      - ../data/processed/title.basics.tsv:/data/title.basics.tsv
      - ../data/processed/title.ratings.tsv:/data/title.ratings.tsv
      - ./sql/02_functions.sql:/docker-entrypoint-initdb.d/02_functions.sql
      - ./sql/01_views.sql:/docker-entrypoint-initdb.d/01_views.sql



  backend:
    image: postgrest/postgrest
    ports:
      - "3000:3000"
    environment:
      PGRST_DB_URI: postgres://authenticator:sps@db:5432/imdb
      PGRST_DB_SCHEMAS: "imdb"
      PGRST_DB_ANON_ROLE: "web_anon"
    depends_on:
      - db

  #load_balancer:
    # TODO

  swagger:
    image: swaggerapi/swagger-ui
    ports:
      - "3001:8080"
    expose:
      - "8080"
    environment:
      API_URL: http://localhost:3000/