# CONFIGURATION FOR PERFORMANCE ANALYSIS

version: '3.1'

services:

  db:
    image: postgres

    environment:
      POSTGRES_DB: imdb
      POSTGRES_USER: authenticator
      POSTGRES_PASSWORD: sps

    # Reources Limits
    mem_limit: 1024m
    mem_reservation: 64M
    cpus: 0.2

    ports:
    # Maps port 5433 on localhost to port 5432 of the container
      - "5433:5432"

    volumes:
      - ../data/processed/title.basics.tsv:/data/title.basics.tsv
      - ../data/processed/title.ratings.tsv:/data/title.ratings.tsv
      - ./sql/:/docker-entrypoint-initdb.d/

  backend:
    image: postgrest/postgrest

    environment:
      PGRST_DB_URI: postgres://authenticator:sps@db:5432/imdb
      PGRST_DB_SCHEMAS: "imdb"
      PGRST_DB_ANON_ROLE: "web_anon"

    # Resources Limits
    mem_limit: 1024m
    mem_reservation: 64M
    cpus: 0.2

    expose:
      - "3000"
    
    depends_on:
      - db

  nginx:

    image: nginx:latest
    
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    
    ports:
      - "3000:80"
    
    depends_on:
      - db

  swagger:
    image: swaggerapi/swagger-ui
    ports:
      - "3001:8080"
    expose:
      - "8080"
    environment:
      API_URL: http://localhost:3000/