# CONFIGURATION FOR DISPATCHING ANALYSIS

version: '2.4'

services:

  db:
    image: postgres
    environment:
      PGPORT: 5432
      POSTGRES_DB: imdb
      POSTGRES_USER: authenticator
      POSTGRES_PASSWORD: sps
      POSTGRES_HOST_AUTH_METHOD: trust
    # Resources Limits
    mem_limit: 1024m
    mem_reservation: 64m
    cpuset: "0"
    ports:
    # Maps port 5433 on localhost to port 5432 of the container
      - "5433:5432"
    volumes:
      - ./sql/:/docker-entrypoint-initdb.d/
      - ./sql/:/sqlFiles/
      - ../data/processed/title.basics.tsv:/data/title.basics.tsv
      - ../data/processed/title.ratings.tsv:/data/title.ratings.tsv
      - ../data/processed/title.crew.tsv:/data/title.crew.tsv
      - ../data/processed/title.episode.tsv:/data/title.episode.tsv


  backend:
    image: postgrest/postgrest
    environment:
      PGRST_SERVER_PORT: 3001
      PGRST_DB_URI: postgres://authenticator:sps@db:5432/imdb
      PGRST_DB_SCHEMAS: "imdb"
      PGRST_DB_ANON_ROLE: "web_anon"
      PGRST_DB_POOL: 100
    # Resources Limits
    mem_limit: 128m
    mem_reservation: 64m
    cpuset: "2"
    ports:
      - "3001-3003:3001"
    depends_on:
      - db


  nginx:
    image: nginx:latest
    volumes:
      # - ./nginx/nginx_dispatching_roundr.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/nginx_dispatching_random.conf:/etc/nginx/nginx.conf:ro
    # Resources Limits
    mem_limit: 128m
    mem_reservation: 64m
    cpuset: "4"
    ports:
      - "3000:80"
    depends_on:
      - db
      - backend