# CONFIGURATION FOR PERFORMANCE ANALYSIS

version: '3.1'

services:

  db:
    image: postgres

    # Reources Limits
    mem_limit: 1024m
    mem_reservation: 64M
    cpus: 0.2

    ports:
    # Maps port 5433 on localhost to port 5432 of the container
      - "5433:5432"
    environment:
      POSTGRES_DB: imdb
      POSTGRES_USER: authenticator
      POSTGRES_PASSWORD: sps
    volumes:
      - ./migrate.sql:/docker-entrypoint-initdb.d/migrate.sql
      - ../data/processed/title.basics.tsv:/data/title.basics.tsv

  backend:
    image: postgrest/postgrest

    # Reources Limits
    mem_limit: 1024m
    mem_reservation: 64M
    cpus: 0.2

    # ports:
    # # Maps port 3000 on localhost to port 3000 of the container
    #   - "3000:3000"
    environment:
      PGRST_DB_URI: postgres://authenticator:sps@db:5432/imdb
      PGRST_DB_SCHEMAS: "imdb"
      PGRST_DB_ANON_ROLE: "web_anon"
    depends_on:
      - db

  nginx:
  # The load balancer
    image: nginx:latest

    # Reources Limits
    mem_limit: 1024m
    mem_reservation: 128M
    cpus: 0.2

    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend
    ports:
    # Maps port 8080 on localhost to port 80 of the container
      - "3000:80"

  swagger:
    image: swaggerapi/swagger-ui

    # Reources Limits
    mem_limit: 1024m
    mem_reservation: 64M
    cpus: 0.2

    ports:
    # Maps port 3001 on localhost to port 8080 of the container
      - "3001:8080"
    expose:
      - "8080"
    environment:
      API_URL: http://localhost:3000/